[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = { key = "${POLYGON_SCAN_API_KEY}", url = "https://rpc.cardona.zkevm-rpc.com" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config